# Generated by Django 2.0.2 on 2018-02-24 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.CharField(max_length=12)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('media_type', models.CharField(choices=[('Book', 'Book'), ('Song', 'Song'), ('Movie', 'Movie')], max_length=5)),
                ('detailed_text', models.TextField()),
                ('title', models.TextField()),
            ],
        ),
    ]
