# Generated by Django 2.0.2 on 2018-03-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popsents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='author',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='month',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='media',
            name='detailed_text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('book', 'Book'), ('movie', 'Movie'), ('song', 'Song')], max_length=5),
        ),
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='media',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
