# Generated by Django 2.0.2 on 2018-03-06 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popsents', '0002_auto_20180304_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompoundSents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('compound', models.DecimalField(decimal_places=3, max_digits=8)),
                ('positive', models.DecimalField(decimal_places=3, max_digits=8)),
                ('neutral', models.DecimalField(decimal_places=3, max_digits=8)),
                ('negative', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='TopSents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('emotion', models.CharField(max_length=20)),
                ('rank', models.IntegerField()),
                ('intensity', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
        ),
        migrations.DeleteModel(
            name='Sentiment',
        ),
    ]
