# Generated by Django 2.0.2 on 2018-03-07 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popsents', '0003_auto_20180306_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='detailed_text',
        ),
    ]
