# Generated by Django 2.0.2 on 2018-03-08 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popsents', '0004_remove_media_detailed_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topsents',
            name='rank',
        ),
    ]
